services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: mini_kv_store
      POSTGRES_USER: kvstore
      POSTGRES_PASSWORD: kvstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data:
